name: Performance Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && startsWith(github.event.deployment_status.target_url, 'https://performance-studio')
    steps:
      - name: Echo target URL
        run: echo "Target URL is ${{github.event.deployment_status.target_url}}"
      - name: Test?
        run: echo "Run the performance studio against ${{github.event.deployment_status.target_url}}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
            - run: git checkout HEAD^
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Debug
        run: node printgit.js
