name: Debug
on:
  push:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Echo target URL
        run: echo "Target URL is ${{github.event.deployment_status.target_url}}"
      - name: Test?
        run: echo "Run the performance studio against ${{github.event.deployment_status.target_url}}"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Debug
        run: node printgit.js
