name: Debug
on:
  push:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Debug
        run: npx ts-node --files --project perf/tsconfig.json perf/git-debug.ts
