name: Store preview build
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && startsWith(github.event.deployment_status.target_url, 'https://performance-studio')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout commit
        # this is required in order for the perf script to find what branches/tags the current commit is on
        run: git reset --hard
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Store preview build
        env:
          BRANCH_DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}
          COMMIT_SHA: ${{ github.event.deployment.ref }}
          PERF_TEST_SANITY_TOKEN: ${{ secrets.PERF_TEST_SANITY_TOKEN }}
          PERF_TEST_METRICS_TOKEN: ${{ secrets.PERF_TEST_METRICS_TOKEN }}
        run: npx ts-node --files --project perf/tsconfig.json perf/storePreviewBuild.ts
